In [1]:
import numpy as np

In [4]:
#Numpy Indexing and Slicing of Vector

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[5]

np.int64(16)

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [11]:
#Numpy Indexing and Slicing of Matrix

In [12]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr[0]

array([1, 2, 3, 4, 5])

In [14]:
arr[4,3]

np.int64(24)

In [15]:
arr[3:7,3:5] #3 start index of row: 7 end index of row goes till 6 , 3 start index of column : 5 end index of column goes till 4

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [17]:
#Boolean Indexing

In [24]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [26]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])