In [4]:
import numpy as np

In [5]:
#Array Operation

In [6]:
#Arithmetic Operation

In [7]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [8]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1-a2

array([-5, -5, -5, -5, -5])

In [10]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1%a2

array([1, 2, 3, 4, 5])

In [13]:
a1//a2

array([0, 0, 0, 0, 0])

In [14]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [15]:
#Broadcasting

In [14]:
l = [10,20,30,40]
arr = np.array(l)

In [15]:
for i in l:#l+10
 i+10

In [16]:
arr+10

array([20, 30, 40, 50])

In [17]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [19]:
#Deep and Shallow Copy

In [20]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice = arr[:5]
slice

array([1, 2, 3, 4, 5])

In [22]:
slice*10

array([10, 20, 30, 40, 50])

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
b = arr[5:7]
b

array([6, 7])

In [25]:
b[0] = 99

In [26]:
arr

array([ 1,  2,  3,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
#Matrix Operation

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
b

array([[5, 6],
       [7, 8]])

In [35]:
a @ b
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [36]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [37]:
a.T

array([[1, 3],
       [2, 4]])

In [7]:
#Advance Array Manipulation

In [8]:
#Stacking Array

In [41]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [42]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
#Splitting Array

In [46]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
a=np.vsplit(c,4)

In [52]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
